config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'messages/index'
  # root to: "messages#index"
  root to: "prototypes#index"
  resources :users, only: [:index, :show]
  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do
  resources :comments, only: :create

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prototype
  belongs_to :user
  validates :content, presence: true

end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :catchphrase, presence: true
  validates :concept, presence: true
  validates :image, presence: true

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 validates :name, presence: true
 validates :profile, presence: true
 validates :occupation, presence: true
 validates :position, presence: true
 
 has_many :comments, dependent: :destroy
 has_many :prototypes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :other_attribute])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(params[:prototype_id])
    @comment = @prototype.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @prototype
    else
      @comments = @prototype.comments.includes(:user)  
      render 'prototypes/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @prototypes = Prototype.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to '/'
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_prototype_owner, only: [:edit, :update, :destroy]
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.all
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to root_path, notice: 'プロトタイプが作成されました'
    else
      render 'new'
    end
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user) 
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to @prototype, notice: 'プロトタイプが更新されました。'
    else
      render :edit, alert: 'プロトタイプの更新に失敗しました。'
    end
  end

  def destroy
    @prototype = Prototype.find(params[:id])
    if @prototype.destroy
      redirect_to prototypes_path, notice: 'プロトタイプが正常に削除されました。'
    else
      redirect_to prototype_path(@prototype), alert: 'プロトタイプの削除に失敗しました。'
    end
  end


  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(:name, :Catchphrase, :catchphrase, :concept, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @prototypes = @user.prototypes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
           <% if user_signed_in? %>
            <div class="nav__right">
               <p>こんにちは <%= link_to current_user.name, user_path(current_user) %> さん</p>
               <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } ,class: :nav__logout %>
               <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div> 
              <% else %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
             <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/messages/_prototype.html.erb
<!-- app/views/messages/_prototype.html.erb -->
<div class="prototype">
  <h2><%= prototype.name %></h2>
  <p><%= prototype.Catchphrase %></p>
  <p><%= prototype.concept %></p>
</div>

app/views/messages/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
      <%# <div class="greeting"> %>
        <%# こんにちは、 %>
        <%# <%= link_to "ユーザー名さん", root_path, class: :greeting__link%>
      <%# </div> %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <h1>All Prototypes</h1>

<% if @prototypes.present? %>
  <% @prototypes.each do |prototype| %>
    <%= render partial: 'prototype', locals: { prototype: prototype } %>
  <% end %>
<% else %>
  <p>No prototypes to display.</p>
<% end %>
<p>No messages to display.</p>
    </div>
  </div>
</main>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :name, "プロトタイプの名称" %><br />
    <%= f.text_field :name, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catchphrase, "キャッチコピー" %><br />
    <%= f.text_area :catchphrase, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="prototype">
  <%# プロトタイプの画像 %>
  <div class="prototype__image">
    <% if prototype.image.attached? %>
      <%= link_to image_tag(prototype.image), prototype_path(prototype) %>
    <% else %>
      <p>画像が見つかりません。</p>
    <% end %>
  </div>

  <%# プロトタイプの名前 %>
  <h2>
    <%= link_to prototype.name, prototype_path(prototype) %>
  </h2>

  <p><%= prototype.catchphrase %></p>
  <p>Posted by: <%= prototype.user.name %></p>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
<%= render 'form' %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'prototype', collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.name %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: :prototype__user %>
      <% if @prototype.user == current_user %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype), method: :delete, data: { confirm: '本当に削除しますか？' }, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <% if @prototype.image.attached? %>
          <%= image_tag @prototype.image %>
        <% else %>
          <p>画像が見つかりません。</p>
        <% end %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catchphrase %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <!-- ログインしているユーザーには以下のコメント投稿フォームを表示する -->
        <% if user_signed_in? %>
          <%= form_with model: [@prototype, @comment], local: true do |f|%>
          <div class="field"> 
             <%= f.label :content, "コメント" %><br /> 
             <%= f.text_field :content, id: "comment_content" %> 
           </div> 
           <div class="actions"> 
             <%= f.submit "送信する", class: :form__btn %> 
           </div> 
        <% end %>
        <% end %>
        <ul class="comments_lists">
            <% @comments.each do |comment| %>
             <li class="comments_list">
               <%= comment.content %> 
               <%= link_to "（#{comment.user.name}）", user_path(comment.user), class: :comment_user %> 
              </li> 
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ" %>
      </h2>
      <div class="user__card">
        <%= render partial: "prototypes/prototype", collection: @prototypes %>
      </div>
    </div>
  </div>
</div>